### ISSUE TITLE
Add Bootstrap classes to make the webpage responsive to different screen sizes

### ISSUE THREAD

**Issue by rimijoker** [rimijoker/Fake_Terminal_Resume_Website#2]
Right now this project lacks responsive web design and due to that, it is difficult to view on devices with smaller screen sizes.

This can be solved by adding necessary bootstrap classes or you may take any other approach which you think will solve this issue.

Please explain the changes in a brief manner in your PR.

**Comment by Utsav-Ladani** [comment]
Hey @rimijoker , I want to make responsive this site. Can I go ahead?

**Comment by rimijoker** [comment]
> Hey @rimijoker , I want to make responsive this site. Can I go ahead?

Sure @Utsav-Ladani 🙂

**Comment by BRAVO68WEB** [comment]
Lets me try too @rimijoker

**Comment by rimijoker** [comment]
> Lets me try too @rimijoker 
> 

Sure @BRAVO68WEB 🙂, you may even collaborate with @Utsav-Ladani

**Comment by Utsav-Ladani** [comment]
> Lets me try too @rimijoker

If you want to try then you can go ahead. I try another issue.
I request @rimijoker to assign this issue to @BRAVO68WEB

**Comment by Utsav-Ladani** [comment]
I don't work on this issue. @BRAVO68WEB you can go ahead instead of me.

**Comment by BRAVO68WEB** [comment]
ok sure i got this @Utsav-Ladani ,
Currently working on it

**Comment by BRAVO68WEB** [comment]
Assign me
@rimijoker

**Comment by BRAVO68WEB** [comment]
@rimijoker Fixed it

**Comment by BRAVO68WEB** [comment]
Please Check

**Comment by BRAVO68WEB** [comment]
@rimijoker ??

**Comment by rimijoker** [comment]
> @rimijoker ??

@BRAVO68WEB  I left some comments on your PR, please take a look.
